version: "3.9"
services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"

  web_api:
    build: . 
    container_name: web_api_application
    ports:
      - "5000:80"
    depends_on:
      - sql
      - redis

  react:
    build: ./react
    ports:
      - "8000:8000"
    volumes:
      - exclude:/front/node_modules/
      - react:/react

volumes:
  exclude:
  react:
